### ISSUE TITLE
Options limit no work

### ISSUE THREAD

**Issue by huangyunbo** [brankosekulic/trimHtml#4]
node.js

html = trimHtml('abcdefghijk', {limit:5});
console.log(html );//{html:'abcdefghijk...',more:true}

limit no work.

57 lines of code in index.js

add = row.substring(cut).split('').indexOf(' ');

row.substring(cut).split('');//is array.   ['f','g','h','i','j','k']

array.indexOf(' ');//Always be -1, here error

**Comment by brankosekulic** [comment]
It's expected behavior since it doesn't break last word.
we can add new option for that e.g. strict: true

**Comment by huangyunbo** [comment]
stringObject.split(separator,howmany) //retrun array

stringObject.indexOf(searchvalue,fromindex) //string!!!

stringObject.split('').indexOf(' ');//Forever -1

**Comment by brankosekulic** [comment]
'test test'.split('').indexOf(' '); // 4

trimHtml('test test', { limit: 2}); // test...

**Comment by huangyunbo** [comment]
sorry,you are right.

stringObject.split(separator,howmany) //retrun array,right too

I hardly use stringObject.split('').indexOf(' ')

Wait for your v0.18.0, Just want to ‘<div>abcde..</div>’.

**Comment by brankosekulic** [comment]
45c1d18e59444df4ff30abf12a8c034d3cd11eba
